<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Log Out_hamburger-one</name>
   <tag></tag>
   <elementGuidId>2a963197-c4fe-4c67-a22c-f708a0bb2208</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='hamburger-one']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#hamburger-one</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b2fc8080-0caf-4f96-a0f7-64b85956ad11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#menu</value>
      <webElementGuid>288f5586-d888-4868-a97e-ab6e97b8bfcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menuTrigger</value>
      <webElementGuid>93d52c1b-17f5-41c9-b2fa-c0c814c13174</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hamburger-one</value>
      <webElementGuid>da27a1ea-72c4-40dc-a6a0-82f959037a45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hamburger-one&quot;)</value>
      <webElementGuid>768c7417-28b8-45fd-b4d3-0bf6cb26dc5a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='hamburger-one']</value>
      <webElementGuid>5c85a36d-2abc-4fce-8a53-59426aebbc9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log Out'])[1]/following::a[1]</value>
      <webElementGuid>4163ba52-8569-43b6-9406-74c6765d1347</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Abdi Narendra Turnip'])[1]/following::a[2]</value>
      <webElementGuid>5ddf5a3a-b386-4b96-8fb3-e5772a1bce44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tuesday October 25 2022 10:33:44'])[1]/preceding::a[1]</value>
      <webElementGuid>5f6c4a3a-2d1e-41aa-aaa2-058dd5b3ac98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#menu')]</value>
      <webElementGuid>416774e6-d09a-4679-912e-5e63ac099904</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a</value>
      <webElementGuid>4e857aab-28bc-4445-bb17-9717d74344b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#menu' and @id = 'hamburger-one']</value>
      <webElementGuid>07884346-2a45-4b24-ad9f-eb07eec7481a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
