<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Menu_mm-next</name>
   <tag></tag>
   <elementGuidId>0bcd8c08-fd31-48b9-8490-7c147f1bf86a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mm-1']/ul/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.mm-next</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>21867aa2-9a53-4b22-a16d-95ca785a9bab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mm-next</value>
      <webElementGuid>a64ad141-856c-4632-9889-f67bebbc97fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#mm-2</value>
      <webElementGuid>32e0999e-e02f-485a-a47a-c0a6834fae04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#mm-2</value>
      <webElementGuid>1e6ba791-df67-4195-a03d-b6b851bc4341</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mm-1&quot;)/ul[@class=&quot;mm-listview&quot;]/li[1]/a[@class=&quot;mm-next&quot;]</value>
      <webElementGuid>ef32ef3c-04c2-46ff-8b30-66a4ca8ddba8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mm-1']/ul/li/a</value>
      <webElementGuid>3800addd-8249-410c-9cf3-0fe5547461c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#mm-2')]</value>
      <webElementGuid>ce1ff5c8-8816-4a37-a109-aaad3d565af6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>51b4381c-5caf-4b54-9bf2-ee0344b89baa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#mm-2']</value>
      <webElementGuid>e72d9772-9e8c-499c-9102-8b677cc157c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
