<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnSearchDataSupplier</name>
   <tag></tag>
   <elementGuidId>c394b5d0-62fc-402e-87fb-83943ded15d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;btnSearch&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;btnSearch&quot;]</value>
      <webElementGuid>7257eef8-8633-4bac-bca7-2a6bf7c7ae0f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
