<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Log Out_FormFrame</name>
   <tag></tag>
   <elementGuidId>51325f43-a40e-45a1-a002-d6ac4da5a9f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='MainContent_FormFrame']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#MainContent_FormFrame</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>18437892-1275-4965-a859-660321f3a709</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MainContent_FormFrame</value>
      <webElementGuid>718636e9-77f3-4b73-9878-429378617d14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FormFrame</value>
      <webElementGuid>c58fa8a0-d702-47ee-b376-817e6ebf1995</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a105214d-be27-47d9-b51d-5d4a2bb4c497</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>3bf9e052-a922-492d-8db5-d3d0efa69e90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5597ccc3-e0be-4ce1-b3e8-e2a3054b71b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>6a04e8d9-f073-4ea2-b42b-cea8da54fd2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>SayMousemove(this.id)</value>
      <webElementGuid>fed3547f-3bbe-4492-8264-bb1be1710130</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseover</name>
      <type>Main</type>
      <value>SayMousemove(this.id)</value>
      <webElementGuid>52bf714b-5637-4a9f-a796-fd68e45cdf0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>Salestrax/AddAsset.aspx</value>
      <webElementGuid>223c19ac-022e-48ee-8330-07ead61ed483</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MainContent_FormFrame&quot;)</value>
      <webElementGuid>777d4683-c718-4991-a13f-ce6073a27321</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='MainContent_FormFrame']</value>
      <webElementGuid>0187c5c4-d7b3-41ef-9d01-09b1b79622fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='intro']/iframe</value>
      <webElementGuid>bd84be7a-0fda-4875-88c6-b57fd8d0acfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>e8cf203a-3762-46ea-bdd4-3796ab258a26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'MainContent_FormFrame' and @name = 'FormFrame' and @src = 'Salestrax/AddAsset.aspx']</value>
      <webElementGuid>ca8b4e24-b54f-4275-8791-f97759836736</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
