<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mother Maiden Name_tbMMName</name>
   <tag></tag>
   <elementGuidId>bd979821-f196-41da-b25f-159055738169</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tbMMName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tbMMName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ea708a17-a091-4b32-a109-f4d62fca8507</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tbMMName</value>
      <webElementGuid>7c846129-be70-4148-ae9c-20d0296ce1fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>87af3e6a-9faf-4570-a58f-b7c64227a3fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tbMMName</value>
      <webElementGuid>d7b50cff-e6d6-416f-b390-82aa88a8cd00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tbMMName&quot;)</value>
      <webElementGuid>423fad64-8124-4e2a-980f-8910457ae757</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_/iframe_Log Out_FormFrame</value>
      <webElementGuid>654a2a02-aebc-4419-9f83-5d70ae035239</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tbMMName']</value>
      <webElementGuid>8d1d3d4f-3912-45fb-b6f6-8120be8cfd0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divLBP']/li[2]/p[2]/input</value>
      <webElementGuid>410d6ce7-9dab-407d-8954-66185491439b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/li[2]/p[2]/input</value>
      <webElementGuid>cb18cfb5-4561-46d6-b1a2-bd18c6e3a411</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'tbMMName' and @type = 'text' and @id = 'tbMMName']</value>
      <webElementGuid>aa61beaf-0904-43d2-883f-e079c09028bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
