<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Reff. Customer_IBCS</name>
   <tag></tag>
   <elementGuidId>9e6ce317-2dbc-490c-95b6-03ecd5836cfc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='IBCS']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#IBCS</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3f549a90-372d-4b35-91ba-a06a3ce2fb3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>54b44994-d212-41f5-b868-0d3dd6bde953</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IBCS</value>
      <webElementGuid>3c7909eb-d50e-475e-b6da-e3a842fc7856</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>IBCS</value>
      <webElementGuid>b5348708-b847-437c-ad50-eb3a01372e47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../Images/search.png</value>
      <webElementGuid>20f011b8-4fa3-41b5-85e5-3401169eebad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>PanggilLookUp('../UserControl/LookupCustomer.aspx?vDlmsRl2qcU=');</value>
      <webElementGuid>ed3b15ee-41d6-443c-9beb-c3263aea9f7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IBCS&quot;)</value>
      <webElementGuid>bc84d0e2-b293-4f3b-9b95-f309e38771e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_/iframe_Log Out_FormFrame</value>
      <webElementGuid>4ebe0691-733f-429c-85cb-cb713b0f4f52</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='IBCS']</value>
      <webElementGuid>2ba2cda3-1b73-40f7-b0b6-38641c726c30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pnlCS']/li/p[2]/input[2]</value>
      <webElementGuid>01e711d5-55a6-4c50-ac40-c6f6cd2100f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/li/p[2]/input[2]</value>
      <webElementGuid>cfb64e70-3de1-4612-9b94-1e9dcb8741f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'IBCS' and @id = 'IBCS' and @src = '../Images/search.png']</value>
      <webElementGuid>8bfe41c5-d47c-4022-89b6-df9e7ad54b19</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
