<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Delete_GRAssetDetailctl02txtAssetName</name>
   <tag></tag>
   <elementGuidId>e96b286f-64a3-474b-9e3b-3c04c91eef85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='GRAssetDetail_txtAssetName_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#GRAssetDetail_txtAssetName_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f3a3adb1-f7bb-4340-9f14-2def8c0b7b80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>GRAssetDetail$ctl02$txtAssetName</value>
      <webElementGuid>67bee305-f1ed-4ab3-b6b1-5eead5e5f6a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>696b921a-ae9d-4c8d-926e-a24d822ef9da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>257a6fb1-4d7f-423d-9817-868de34ea09d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>GRAssetDetail_txtAssetName_0</value>
      <webElementGuid>6145922a-5d60-4979-8db0-c364baaba0f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GRAssetDetail_txtAssetName_0&quot;)</value>
      <webElementGuid>16246a84-5f55-4c81-ad01-3723bf53bb98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_/iframe_Log Out_FormFrame</value>
      <webElementGuid>e8818d9e-7377-4031-a9fd-7150aebed44e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='GRAssetDetail_txtAssetName_0']</value>
      <webElementGuid>63524c67-1789-4796-b7be-13079078129a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='GRAssetDetail']/tbody/tr/td[2]/input</value>
      <webElementGuid>575a2f62-0453-4791-be58-12056d408772</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>74ecd62b-d76b-474c-ac1b-b32442a5647c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'GRAssetDetail$ctl02$txtAssetName' and @type = 'text' and @id = 'GRAssetDetail_txtAssetName_0']</value>
      <webElementGuid>eb2c7b32-0aaa-438c-a8c3-efe81819a0f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
