<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Supplier_csLookup</name>
   <tag></tag>
   <elementGuidId>e6e2aec7-9c6a-4ff0-8ea7-1ff3a40f01a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='csLookup']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#csLookup</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>52ca7002-6c06-44fa-b471-532689d5849a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>c83aee6f-997f-479c-8685-f379496ff70e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>csLookup</value>
      <webElementGuid>fa773906-dea3-4d1d-a0cc-731836b2f15e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>csLookup</value>
      <webElementGuid>be5f4937-605a-443a-9b7f-70f8fa842a8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../Images/search.png</value>
      <webElementGuid>a343072a-9ae3-4a6b-8143-5ded419e0184</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>PanggilLookUp('../UserControl/LookupSupplier.aspx?s5L06Oa9poQNl4DEyiMv6OXfujMATmBC');</value>
      <webElementGuid>df6872b3-8e00-4957-9845-6577804ecef0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;csLookup&quot;)</value>
      <webElementGuid>744852f4-832c-472b-b260-5e07250847c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_/iframe_Log Out_FormFrame</value>
      <webElementGuid>3ace2ac5-8352-4a8e-83ea-dca6dfd888ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='csLookup']</value>
      <webElementGuid>cb04937b-eaf0-406d-98a7-0d31d4a29834</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='isi']/ul/li[6]/p[2]/input[2]</value>
      <webElementGuid>01c5a529-8f49-4508-af4e-fa8e82958321</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/p[2]/input[2]</value>
      <webElementGuid>5a94fd2c-950e-4d2f-b5f2-c9df39c5543a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'csLookup' and @id = 'csLookup' and @src = '../Images/search.png']</value>
      <webElementGuid>3cbebebb-1339-4e23-8b43-94843019b132</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
