<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Abdi Narendra Turnip_GRAddAssetctl03b_cb8e95</name>
   <tag></tag>
   <elementGuidId>ab8dadd4-35ed-4e16-842c-73e759ee0bcd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='GRAddAsset_btnupdate_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#GRAddAsset_btnupdate_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fbafb1bf-8d4b-4cf3-9a98-e4c613361413</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>9b29e865-ebe0-4063-bb22-98568f6e4603</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>GRAddAsset$ctl03$btnupdate</value>
      <webElementGuid>b11d2a24-9c0c-4e29-9116-307ee0f15afe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>GRAddAsset_btnupdate_1</value>
      <webElementGuid>4f5c1e45-9e6c-4a95-b74e-09a8b384db93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../Images/file_Edit.png</value>
      <webElementGuid>01fba07a-16aa-47e2-a2a7-2770d3ff4ea8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GRAddAsset_btnupdate_1&quot;)</value>
      <webElementGuid>c372a0c9-ff5c-4996-83cb-89e227f7dbe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_/iframe_Log Out_FormFrame</value>
      <webElementGuid>b440409b-e871-4c40-b9e7-dc68419086be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='GRAddAsset_btnupdate_1']</value>
      <webElementGuid>5413d9c6-158a-4811-8d19-250ef24d50c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='GRAddAsset']/tbody/tr[2]/td[5]/input</value>
      <webElementGuid>1b14171a-f53d-47b6-b7e1-b04289944b59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[5]/input</value>
      <webElementGuid>3c1efca6-e78a-4547-8435-2383dd76287c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'GRAddAsset$ctl03$btnupdate' and @id = 'GRAddAsset_btnupdate_1' and @src = '../Images/file_Edit.png']</value>
      <webElementGuid>15b522c1-86c7-4978-9ab1-43cd4c90735f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
