<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SUPPLIER RATING_rbtSupplier</name>
   <tag></tag>
   <elementGuidId>cb1be550-02c1-4d76-99d8-0122efe5c120</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='rbtSupplier']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;rbtSupplier&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c2374aff-a7a4-4bbb-b496-f6198937d970</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>2ad4cd64-8e30-412c-bd18-555963a560be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rbtSupplier</value>
      <webElementGuid>4e2a504e-e2e7-4f78-9624-45fe3ce16b5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:Supplier_Checked('OTUPETXM','Supplier Individu')</value>
      <webElementGuid>863343ae-8184-4b77-9f48-c8dba687156a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GRSupplier&quot;)/tbody[1]/tr[@class=&quot;tdganjil&quot;]/td[@class=&quot;expand footable-visible footable-first-column&quot;]/input[1]</value>
      <webElementGuid>05ee786b-3283-4cd2-bb35-0f973fc7762d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='rbtSupplier']</value>
      <webElementGuid>8119594c-2e0f-4ac9-8fc8-e39a17394663</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='GRSupplier']/tbody/tr/td/input</value>
      <webElementGuid>f2a5fb40-d015-45ac-9156-da35f89ff1f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>7f537cf7-1282-4ea5-967f-5cf93793ad49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'rbtSupplier']</value>
      <webElementGuid>d799f747-a3c6-4a5a-958d-372f1b2c1073</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
