<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Delete_GRAssetDetailctl02txtNTF</name>
   <tag></tag>
   <elementGuidId>9141eb40-988d-4c6a-b986-718d6bae80f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='GRAssetDetail_txtNTF_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#GRAssetDetail_txtNTF_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6055333c-2c9b-4bd1-bff4-b6d590a296ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>GRAssetDetail$ctl02$txtNTF</value>
      <webElementGuid>06674825-4c78-4dc5-bdbf-f5fd3a473ad4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f2ce1768-f957-4d4f-8628-463949de7043</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>bd2d48a1-7524-4b33-bafc-4e40b7132595</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>17</value>
      <webElementGuid>cbc49142-272b-461b-bfad-a1909d8b1277</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>GRAssetDetail_txtNTF_0</value>
      <webElementGuid>aea511b9-1a0c-4c4f-bb6b-ab305aa4152a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>money</value>
      <webElementGuid>0adaf381-f7d1-40b9-9fea-eb993072c334</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return ValidateMoney(event, this);</value>
      <webElementGuid>6bfe2124-00ed-43ef-8fa1-0c48ac884a9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>checkTextField1(this);</value>
      <webElementGuid>58da218c-d4a2-4f92-8cb4-e34a68b14abd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GRAssetDetail_txtNTF_0&quot;)</value>
      <webElementGuid>06015204-3207-45aa-9519-167704ea6641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_/iframe_Log Out_FormFrame</value>
      <webElementGuid>631c1825-f4cb-4efa-a1b9-3e7425cc6357</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='GRAssetDetail_txtNTF_0']</value>
      <webElementGuid>8b65b87a-cb96-4acc-8740-08e1d6515995</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='GRAssetDetail']/tbody/tr/td[8]/input</value>
      <webElementGuid>2670a24d-3dbc-4983-81ce-a21c300f65c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/input</value>
      <webElementGuid>8138448e-c540-446a-ad3b-c44d1b9f0957</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'GRAssetDetail$ctl02$txtNTF' and @type = 'text' and @id = 'GRAssetDetail_txtNTF_0']</value>
      <webElementGuid>2c07d23a-4b9e-4b45-9567-e3376970ccd2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
