<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Delete_GRAssetDetailctl02txtFunding</name>
   <tag></tag>
   <elementGuidId>a7cc7f39-53c8-4c8a-8e4c-6f2b364f5aa9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='GRAssetDetail_txtFunding_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#GRAssetDetail_txtFunding_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ffe8e641-d280-44be-855f-a5a32a183ba8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>GRAssetDetail$ctl02$txtFunding</value>
      <webElementGuid>e89308b2-ad74-49f8-a4e6-145bd27fc2b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1aabd220-15cd-4f99-ad1f-64d3c395479d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e864d7c7-3525-437b-b305-6229b4a192d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>17</value>
      <webElementGuid>2ed5792c-ebd0-4e18-afba-8792cda46899</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>GRAssetDetail_txtFunding_0</value>
      <webElementGuid>44cc2f85-e81e-493d-85bc-c7d3291e987b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>money</value>
      <webElementGuid>42e19f55-eedd-484e-bff8-b71a78708d2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return ValidateMoney(event, this);</value>
      <webElementGuid>60449403-8016-43b4-af8b-655c17259e08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>checkTextField1(this);</value>
      <webElementGuid>ae57e5dd-9d4d-4eef-aa14-1c2268658926</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GRAssetDetail_txtFunding_0&quot;)</value>
      <webElementGuid>404310b3-776f-407d-8a08-76b564485561</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_/iframe_Log Out_FormFrame</value>
      <webElementGuid>804098d6-2ef0-43c6-9026-3f6ffe7ff5ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='GRAssetDetail_txtFunding_0']</value>
      <webElementGuid>3cb4af9d-0637-42ff-9d3d-6faa77dffd5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='GRAssetDetail']/tbody/tr/td[7]/input</value>
      <webElementGuid>c07fe9f9-178f-4d5f-8873-bed3b33e4c9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/input</value>
      <webElementGuid>2861d267-3170-4791-85dd-481d4568dcb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'GRAssetDetail$ctl02$txtFunding' and @type = 'text' and @id = 'GRAssetDetail_txtFunding_0']</value>
      <webElementGuid>99a8357d-019a-41ad-bbf8-789073fdc193</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
