<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_KOTA MEDAN_rbtGridSelect</name>
   <tag></tag>
   <elementGuidId>81a25d85-06f5-4bbe-bb3f-d950c5276c1b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='rbtGridSelect'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ae40cee3-429f-4bdc-bf4c-542918e89433</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>84512e2b-64b0-47b3-a05f-a236c6566611</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rbtGridSelect</value>
      <webElementGuid>fc175fff-30b1-44d7-b8d5-17229f20f12b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:Grid_Checked('AMPLAS' ,'MEDAN AMPLAS', 'MEDAN' ,'20229')</value>
      <webElementGuid>b6c9e663-290c-45e7-89ae-6639fc3df7ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GRCustomer&quot;)/tbody[1]/tr[@class=&quot;tdganjil&quot;]/td[@class=&quot;expand footable-visible footable-first-column&quot;]/input[1]</value>
      <webElementGuid>fb781d53-74c0-488e-a49c-3ebe72173a35</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='rbtGridSelect'])[3]</value>
      <webElementGuid>38a86762-b962-4ca5-80cc-681bffb2068f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='GRCustomer']/tbody/tr[3]/td/input</value>
      <webElementGuid>d45741ff-1faa-42af-a76f-da8753f6fffc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/input</value>
      <webElementGuid>8a129415-508e-4149-aa3a-abe87f05dc7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'rbtGridSelect']</value>
      <webElementGuid>51655b82-f375-4a4b-af7b-4391777f2260</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
