<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Zipcode_ZipCode</name>
   <tag></tag>
   <elementGuidId>eb01f7de-d0cb-4907-b9f7-235e4a601530</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ZipCode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ZipCode</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fcd2f58b-4c50-4f7f-bf64-0fdd86aeb506</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>9f731ebd-4ffb-40a0-9d03-a9e07bbd7a09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ZipCode</value>
      <webElementGuid>679037d7-be7a-421b-aaa2-c654faa98fe4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ZipCode</value>
      <webElementGuid>ffe31cfd-3a61-46f2-ab82-c2c4529b7df2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../Images/search.png</value>
      <webElementGuid>9fab8d49-1188-459e-b58c-ec75c7efc48d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>openLookup();return false;</value>
      <webElementGuid>4387036e-78bc-4df7-b90d-6800502dd0e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ZipCode&quot;)</value>
      <webElementGuid>5a0f33a7-299d-45aa-88f4-97678fa1dae8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_/iframe_Log Out_FormFrame</value>
      <webElementGuid>8ec4ab4f-9154-47b0-b7ab-8700ac02f87c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ZipCode']</value>
      <webElementGuid>7dc0e12b-a99f-4ec3-9d58-8444898053e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pnlzipcode']/li/p[2]/input[3]</value>
      <webElementGuid>9de8c354-b3bb-44dc-a511-2cd6044f0035</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/li/p[2]/input[3]</value>
      <webElementGuid>543f81b0-3517-4c17-93c5-096808e888f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'ZipCode' and @id = 'ZipCode' and @src = '../Images/search.png']</value>
      <webElementGuid>90f96a76-7e6f-4c96-a7d9-ea3a35ce1099</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
