<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Delete_GRAssetDetailctl02tbExpiredDat_0c4228</name>
   <tag></tag>
   <elementGuidId>3edd888f-e9b9-4e95-9ec1-1ed65384bb24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='GRAssetDetail_tbExpiredDateNoticePajak_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#GRAssetDetail_tbExpiredDateNoticePajak_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>82f41573-e627-4d35-8f4b-0d26b02a418a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>GRAssetDetail$ctl02$tbExpiredDateNoticePajak</value>
      <webElementGuid>db8d16c9-cb8c-40e9-9018-329c4530cf41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>62155f35-8752-450e-80ac-703baec9a690</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>GRAssetDetail_tbExpiredDateNoticePajak_0</value>
      <webElementGuid>aa9050fe-6005-4233-99b6-9a68efe634b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tanggal hasDatepicker</value>
      <webElementGuid>eb092d3c-812c-4a5b-8895-1ca185c260ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>a6f6246b-a85b-45ec-8c07-0dd0e33f773e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GRAssetDetail_tbExpiredDateNoticePajak_0&quot;)</value>
      <webElementGuid>9a9e3421-bc2b-4450-84a9-f3c68aae7a07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_/iframe_Log Out_FormFrame</value>
      <webElementGuid>678fcce1-4ad2-4154-b394-243bd7a104fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='GRAssetDetail_tbExpiredDateNoticePajak_0']</value>
      <webElementGuid>c07e041b-42b6-4527-bb9c-ed462a9eff8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='GRAssetDetail']/tbody/tr/td[13]/input</value>
      <webElementGuid>bd252859-ae52-412a-9972-584a96d724a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[13]/input</value>
      <webElementGuid>6684508f-daf1-46ae-be3b-d14c07e8164b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'GRAssetDetail$ctl02$tbExpiredDateNoticePajak' and @type = 'text' and @id = 'GRAssetDetail_tbExpiredDateNoticePajak_0']</value>
      <webElementGuid>4f38dfca-6a73-400c-b0fe-4b5044a68d9c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
