<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Delete_GRAssetDetailctl02txtYear</name>
   <tag></tag>
   <elementGuidId>2c618bf5-127e-46dd-9de9-d4118c45a35b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='GRAssetDetail_txtYear_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#GRAssetDetail_txtYear_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c3737e22-4e49-496c-87ef-0cde974ec9d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>GRAssetDetail$ctl02$txtYear</value>
      <webElementGuid>45497391-ab3b-4998-b0a5-40c56ca7143e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9f94e877-5d88-4331-93cc-6abbabb1e368</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>62287607-e4e0-4eaf-95ba-1a8c157a39da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>1a7ae308-b58f-420d-88f3-aab524a68d04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>GRAssetDetail_txtYear_0</value>
      <webElementGuid>2b48f60f-8a44-4a44-8f70-32db91421350</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return isnumerickey(event);</value>
      <webElementGuid>b5fb799f-a41c-4614-aff9-6d97df0e2ea9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GRAssetDetail_txtYear_0&quot;)</value>
      <webElementGuid>b9370dbf-8bea-4cbe-9722-dc7a05a797de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_/iframe_Log Out_FormFrame</value>
      <webElementGuid>e52d90e1-7564-4680-ba76-718f70d507b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='GRAssetDetail_txtYear_0']</value>
      <webElementGuid>f0284167-4df8-4549-b4cf-9b8ecd5cb06a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='GRAssetDetail']/tbody/tr/td[3]/input</value>
      <webElementGuid>3816438c-c891-4511-bc87-ee2c68bbeee4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/input</value>
      <webElementGuid>619cecc5-a68a-4f7c-ab29-9177abf0dc56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'GRAssetDetail$ctl02$txtYear' and @type = 'text' and @id = 'GRAssetDetail_txtYear_0']</value>
      <webElementGuid>ee8006cd-750b-4257-a18d-3ce8012816e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
