<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selectSerachBy_DataCustomer</name>
   <tag></tag>
   <elementGuidId>d351e532-23ea-4413-b80a-07e8ac392176</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;ddlsearch&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;ddlsearch&quot;]</value>
      <webElementGuid>1978221a-0f9b-4d03-b202-f46848ade266</webElementGuid>
   </webElementProperties>
</WebElementEntity>
