<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Log Out_FormFrame</name>
   <tag></tag>
   <elementGuidId>5f0bd789-e91d-48f3-968e-6cb627febf7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#MainContent_FormFrame</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='MainContent_FormFrame']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>37d8eb3d-66a3-4304-9cc6-9c83dec1491a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MainContent_FormFrame</value>
      <webElementGuid>7a599676-57b3-4e99-9189-b67bacfc7fef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FormFrame</value>
      <webElementGuid>dab8cbd4-8c8a-4cf9-90da-0f0886bc4289</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9d959ad6-4293-451b-9057-0da436b57a98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>f04c230e-bfb9-474d-89b8-06e70cf1881f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9f40a7cc-f72f-43cd-95ea-c805da0428ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>7bc1cb9d-f62a-4d7e-8c02-b93fcd434920</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>SayMousemove(this.id)</value>
      <webElementGuid>1077c3cb-7c3f-4118-841a-2d1154694ff5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseover</name>
      <type>Main</type>
      <value>SayMousemove(this.id)</value>
      <webElementGuid>0845d24f-af17-4939-8aa2-182c6a625451</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>Salestrax/InputCustomer.aspx</value>
      <webElementGuid>88146326-b76b-4d6d-bf9d-f32cae623ceb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MainContent_FormFrame&quot;)</value>
      <webElementGuid>cbd9dc8f-a735-483e-add0-178e7a415c8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='MainContent_FormFrame']</value>
      <webElementGuid>8d583bc6-34e2-4eda-8101-4378add75671</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='intro']/iframe</value>
      <webElementGuid>84780cbd-eff1-44b0-8882-5b6347ace7ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>9c75b334-4a09-424a-8b6e-1d706579c73b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'MainContent_FormFrame' and @name = 'FormFrame' and @src = 'Salestrax/InputCustomer.aspx']</value>
      <webElementGuid>1c7b3e9a-2dc2-46fe-812a-06b9d9941d22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
