<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_companyPhone</name>
   <tag></tag>
   <elementGuidId>cc45518f-7b91-417b-a017-c750dec6bc87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtCPTelp</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtCPTelp']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7ba890b1-e154-4a94-80e3-29142811ba51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtCPTelp</value>
      <webElementGuid>4ea452a8-ed72-4d8f-9f98-ad7504c910bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b95fff49-5644-4e43-ae2c-4ffbbcbb3a05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>47fb5256-745b-4cbb-8da8-1f3849b4ba44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtCPTelp</value>
      <webElementGuid>00fd755a-18d3-4cf7-b91c-a4214b4a1a5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>validate[custom[phone]]</value>
      <webElementGuid>fb1d15de-74ec-430c-b097-854dd42e18f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Phone Number</value>
      <webElementGuid>b90b3cca-68fc-478f-a616-4c4391fa7b8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtCPTelp&quot;)</value>
      <webElementGuid>c34c7d60-d7ce-4558-bf38-64a5883b92a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_InputCustomer/iframe_Log Out_FormFrame</value>
      <webElementGuid>d5ed0b84-49fc-4b4f-a4a7-c7e3e63d1c1f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtCPTelp']</value>
      <webElementGuid>8599d350-7bc8-47f1-8291-0dd2ec1b4896</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='isi']/ul/li[9]/p[2]/input[2]</value>
      <webElementGuid>7ed7986b-5a62-4717-a702-b41b4e0276e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[9]/p[2]/input[2]</value>
      <webElementGuid>7f256367-64fa-49fd-aff4-469ceb28ad98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'txtCPTelp' and @type = 'text' and @id = 'txtCPTelp' and @placeholder = 'Phone Number']</value>
      <webElementGuid>140bdb85-fb8d-47fe-a0c3-9f36fd5af10d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
