<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_companyArea</name>
   <tag></tag>
   <elementGuidId>02a1249b-2a9c-4897-9f7c-1da0c5b5fa9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtCPArea</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtCPArea']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e76004a6-4bbe-42b7-a01d-13a2987820e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtCPArea</value>
      <webElementGuid>2c239a2c-c976-41c0-8d75-4ddcadb06b2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8ab5329d-4df7-461a-8a91-292bcc9e4072</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>c3623baf-db11-4c55-8a3d-074af765a53d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtCPArea</value>
      <webElementGuid>3640eaa7-a312-4ea6-8542-3a617fac3efd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>area validate[custom[phone]]</value>
      <webElementGuid>caf998c6-ac7c-41ed-b72a-18da4d122502</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Area</value>
      <webElementGuid>bd186c7f-433d-4c7b-9310-dbf2fce6e65c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtCPArea&quot;)</value>
      <webElementGuid>d9695762-1292-44cc-9dee-87fca5ade844</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_InputCustomer/iframe_Log Out_FormFrame</value>
      <webElementGuid>caae129d-8308-4298-bbfb-8188d2838baf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtCPArea']</value>
      <webElementGuid>83c3b38e-00a6-4621-bef6-b325a688ed1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='isi']/ul/li[9]/p[2]/input</value>
      <webElementGuid>e97c9fdf-95bd-4e9a-be9a-9384f84d9e72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[9]/p[2]/input</value>
      <webElementGuid>a66879a1-4564-47a5-b25a-5c282c1707ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'txtCPArea' and @type = 'text' and @id = 'txtCPArea' and @placeholder = 'Area']</value>
      <webElementGuid>f6eaa068-66ee-42c4-82ae-9d8462d4afcf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
