<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_residenceArea</name>
   <tag></tag>
   <elementGuidId>f98e6415-55cc-46ac-ac15-544653415bc2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtRParea</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtRParea']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d197da9b-11eb-4dd8-b7e5-cfb9471d3f72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtRParea</value>
      <webElementGuid>4242f8cd-4891-4a45-989a-35822a819277</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>089816d6-bfa7-4893-9dcd-2c40af1790fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>a4006f94-c495-44b2-9dd4-2fab127e6967</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtRParea</value>
      <webElementGuid>c0a5b3b8-23d8-4f0c-a4fb-e4573abda473</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>area validate[custom[phone]]</value>
      <webElementGuid>8535b47a-a9c2-49c7-a67e-e9135b08620d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Area</value>
      <webElementGuid>c9913f29-5321-4e93-b328-a25852a6d592</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtRParea&quot;)</value>
      <webElementGuid>67f86233-1bc4-478b-aa4f-ecbce75e4158</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_InputCustomer/iframe_Log Out_FormFrame</value>
      <webElementGuid>eaeadcaa-1932-4eed-80ab-d9dd12f5421e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtRParea']</value>
      <webElementGuid>acf8023b-e5db-4584-95d3-ed55a3e107bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='isi']/ul/li[8]/p[2]/input</value>
      <webElementGuid>db495390-0215-496e-bc75-d29ccc13b1e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/p[2]/input</value>
      <webElementGuid>433e3068-4e00-4625-bd7d-bb20c2c17233</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'txtRParea' and @type = 'text' and @id = 'txtRParea' and @placeholder = 'Area']</value>
      <webElementGuid>5c2e8ef1-bf50-4c80-a0a0-f8e81916ba54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
