<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_customerName</name>
   <tag></tag>
   <elementGuidId>37051234-9439-4881-bfb1-ba8ab9a26320</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtCN</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtCN']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f8e97650-732f-43b0-bd52-b7bd6a38bbb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtCN</value>
      <webElementGuid>ccac5073-09ea-45ac-a228-e47e0789cca2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>11cc6a17-be3d-4eff-8d9f-bf0d1a5bbaea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>f7d3758d-f5b1-40c4-9579-6a91142a07d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtCN</value>
      <webElementGuid>c40cafe9-0310-4729-9ef8-148bddee9417</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>validate[required,custom[onlyLetterSp]]</value>
      <webElementGuid>cd56dba7-d74f-41de-bf77-26da07a8435c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtCN&quot;)</value>
      <webElementGuid>6868c04b-b918-4820-804c-f4f27387d858</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_InputCustomer/iframe_Log Out_FormFrame</value>
      <webElementGuid>8482c1f4-0a7d-469a-82c2-00e5af813f95</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtCN']</value>
      <webElementGuid>8b752951-e9aa-4c0a-ab4a-7a4bbf373853</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='isi']/ul/li[5]/p[2]/input</value>
      <webElementGuid>9a78006b-bf7f-4449-9676-caa82530f1ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>4df3180a-1143-4737-8869-967ba6e26791</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'txtCN' and @type = 'text' and @id = 'txtCN']</value>
      <webElementGuid>9cd15d8a-5c0a-4d5d-a8b3-6a21aa018c0f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
