<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_residencePhone</name>
   <tag></tag>
   <elementGuidId>db62088e-38cc-4754-803c-843bed3445b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtRPTelp</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtRPTelp']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>61d3688e-e6f4-4665-acbc-5f206531980f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtRPTelp</value>
      <webElementGuid>8e783203-091f-45d1-9a17-8064a4528a08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cb21106e-b10e-47f2-ba48-9580af812926</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>4515292b-c133-466c-afd3-f65856bf6866</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtRPTelp</value>
      <webElementGuid>84fb4513-4282-4bc1-92fd-91d511671581</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>validate[custom[phone]]</value>
      <webElementGuid>5b0988ff-5d97-44c4-a39e-d5d13254fa6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Phone Number</value>
      <webElementGuid>053efb50-df49-46ef-a62e-9bb9cc38db7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtRPTelp&quot;)</value>
      <webElementGuid>aa31dcc6-b8c8-4f4d-99ed-8b5bbfbec678</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_InputCustomer/iframe_Log Out_FormFrame</value>
      <webElementGuid>d54b58d1-bd1b-4a89-994d-02ef5ab149ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtRPTelp']</value>
      <webElementGuid>7cb9eb14-5da8-4760-b5cb-3245131168ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='isi']/ul/li[8]/p[2]/input[2]</value>
      <webElementGuid>85ed308f-496e-4bf6-8a0a-b20a3211d4cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>72ca515e-e9b0-44cb-b21b-64f1232180c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'txtRPTelp' and @type = 'text' and @id = 'txtRPTelp' and @placeholder = 'Phone Number']</value>
      <webElementGuid>0d79d47c-0d83-4ad3-80cf-4785dc9215ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
