<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_birthDate</name>
   <tag></tag>
   <elementGuidId>2df2b86c-e820-47e2-90f9-2c0b6bd5b9f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtDate</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'txtDate' and @type = 'text' and @id = 'txtDate' and @ref_element = 'Object Repository/Page_/iframe_Log Out_FormFrame']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d94a21f4-310a-4bcf-84e7-3f46f6d5783c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtDate</value>
      <webElementGuid>9aba4d3d-02d5-4e06-9715-6a21ddd00d17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ff9bc013-d5a6-4247-ab0e-cde801d39249</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtDate</value>
      <webElementGuid>76c97193-e862-4058-8e50-a142422da3d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tanggal hasDatepicker</value>
      <webElementGuid>96bb5c3d-d58f-419b-8dfa-c4ca8e7386c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>c3110618-c050-4e27-b90b-cfc8efef2bf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtDate&quot;)</value>
      <webElementGuid>c63c3ad9-0a47-491c-9b51-e8b81dc5fcb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_InputCustomer/iframe_Log Out_FormFrame</value>
      <webElementGuid>4207eb3a-1239-421e-9e6b-4cebd6b9f37d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtDate']</value>
      <webElementGuid>467cd8de-bce6-4bfd-a8e1-dc9d13a3fb07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='isi']/ul/li[13]/p[2]/input</value>
      <webElementGuid>a51f31d3-c4c1-4cd6-8751-f2646a1dc084</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[13]/p[2]/input</value>
      <webElementGuid>8792b719-5aa3-4688-8dba-e8f1f3088d29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'txtDate' and @type = 'text' and @id = 'txtDate']</value>
      <webElementGuid>5e62a269-b93e-40ad-b32f-f92f0046276f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
