<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_mobilePhone</name>
   <tag></tag>
   <elementGuidId>e6036376-4b79-46eb-977c-467e0c829fab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtMP</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtMP']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c9d1528f-17d0-490e-9276-a2c147d49542</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtMP</value>
      <webElementGuid>872d2b52-8b04-4c56-9eac-d3d28a92e5f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1508b057-6351-472b-9977-371f761aad41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>d55d8269-d996-4f78-8b3b-2003c5120b89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtMP</value>
      <webElementGuid>efcc7764-8db2-4a30-a7b8-5cdf9ed1ca8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>validate[required,custom[integer]]</value>
      <webElementGuid>e9fab29e-3431-49f8-9a29-82abe41bb957</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtMP&quot;)</value>
      <webElementGuid>176b0900-6638-49b9-af62-280323dec8ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_InputCustomer/iframe_Log Out_FormFrame</value>
      <webElementGuid>df3f1c90-5352-47a0-b65f-ecae842574b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtMP']</value>
      <webElementGuid>d797cfbd-48fe-4da8-b3d1-1dcda86eb823</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='isi']/ul/li[7]/p[2]/input</value>
      <webElementGuid>e392efa2-b3a4-49de-ae0a-18d24efecb6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/p[2]/input</value>
      <webElementGuid>54f80b34-8bc9-438f-8086-48a0b7487c51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'txtMP' and @type = 'text' and @id = 'txtMP']</value>
      <webElementGuid>c80e5fd3-dda4-4f4c-bba7-e97b9965e550</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
