<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_IDNumber(KTP)</name>
   <tag></tag>
   <elementGuidId>13e01172-4edc-4ac7-a777-3422be114bd8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtKTP</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtKTP']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f2abb398-0404-4de3-932a-a049c1a577f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtKTP</value>
      <webElementGuid>7b392dcb-3b35-43da-8c6b-0758806abb14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9d2168fc-a791-44e4-ad2f-948f7b338ce4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>1c49f5be-6e39-4dc6-83c9-2e92ca5824fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtKTP</value>
      <webElementGuid>4fead5d5-672a-4174-91f8-896109c1eba3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>validate[custom[integer]]</value>
      <webElementGuid>d90ee988-85f0-4663-9a59-593036041c2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtKTP&quot;)</value>
      <webElementGuid>8fe5e7f8-dcf8-4600-a8ab-0140c63d72f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_InputCustomer/iframe_Log Out_FormFrame</value>
      <webElementGuid>b85c8afc-318e-4811-8042-4cb85fc21fe0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtKTP']</value>
      <webElementGuid>f714eb35-75eb-4c4c-b973-f9c0d4fead4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='isi']/ul/li[11]/p[2]/input</value>
      <webElementGuid>ba793d2b-befb-4103-b326-6059d9bbfba5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[11]/p[2]/input</value>
      <webElementGuid>366cd605-3ab2-48ab-a791-7fd0541f51a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'txtKTP' and @type = 'text' and @id = 'txtKTP']</value>
      <webElementGuid>a840ede6-aac9-4bb0-b795-55568454fc3d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
