<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>menuSalestrax</name>
   <tag></tag>
   <elementGuidId>ca9faf9e-18a0-4d17-b879-763a5ef7f987</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.mm-next</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mm-1']/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a37aba8b-a6ab-4d37-a17b-8772212251dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mm-next</value>
      <webElementGuid>9e26b780-b605-424e-b982-f653117d854f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#mm-2</value>
      <webElementGuid>6f0ca672-b822-466d-9ae7-5d5d39db70e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#mm-2</value>
      <webElementGuid>202d28e1-305d-453d-a836-5d2db935faa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mm-1&quot;)/ul[@class=&quot;mm-listview&quot;]/li[1]/a[@class=&quot;mm-next&quot;]</value>
      <webElementGuid>f50d6953-55a9-4849-9463-710c095b4994</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mm-1']/ul/li/a</value>
      <webElementGuid>54767d49-c35d-4011-abf5-d624d1334a5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#mm-2')]</value>
      <webElementGuid>8e0cf76d-d288-4aad-8d69-9db773bee955</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>9e5e8cce-0bc4-46fe-ada4-57995a0d6963</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#mm-2']</value>
      <webElementGuid>28126775-5044-4c7c-ac5f-1566dd2aab29</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
