<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_maritalStatus</name>
   <tag></tag>
   <elementGuidId>8e563ccf-af87-4452-abd6-4a4adf57ff34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ddlMarital</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ddlMarital']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5bae7065-9dbd-43e5-b15f-eb2c3b66eb19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ddlMarital</value>
      <webElementGuid>0c15f2f0-8888-4625-a214-4ef011fd8559</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ddlMarital\',\'\')', 0)</value>
      <webElementGuid>82804797-86f5-449a-aec1-c9636aa16dfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ddlMarital</value>
      <webElementGuid>5b91d929-70ca-436f-bdf6-98ae4e177cb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
	Select One
	Divorce
	Married
	Single
	Widow

</value>
      <webElementGuid>96228c0c-647f-4a49-8455-756141aa736b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ddlMarital&quot;)</value>
      <webElementGuid>a115bb15-d80e-4d9a-8f9f-1fe31e6d7cae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_InputCustomer/iframe_Log Out_FormFrame</value>
      <webElementGuid>f5138a58-bd30-4448-ae55-dd3abb70c16d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ddlMarital']</value>
      <webElementGuid>38b0b343-1adc-4bf8-9e2e-1ae7d5006cbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='isi']/ul/li[14]/p[2]/select</value>
      <webElementGuid>cb8f81d7-c122-4e4e-897b-f9994d7948d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Marital Status'])[1]/following::select[1]</value>
      <webElementGuid>a28574c4-3036-472b-be90-fbae9b81fd28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BirthDate'])[1]/following::select[1]</value>
      <webElementGuid>37b5404c-5e45-4d4f-bfed-59968680ce17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-- Job Data --'])[1]/preceding::select[1]</value>
      <webElementGuid>742e19b6-8034-4da1-b685-7074d147da85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Profession'])[1]/preceding::select[1]</value>
      <webElementGuid>84c6d523-b942-4039-8ac3-05002194987f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[14]/p[2]/select</value>
      <webElementGuid>2ba86f7e-8b6f-4b5b-827a-380461ed2145</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'ddlMarital' and @id = 'ddlMarital' and (text() = '
	Select One
	Divorce
	Married
	Single
	Widow

' or . = '
	Select One
	Divorce
	Married
	Single
	Widow

')]</value>
      <webElementGuid>27c0b0ed-8e23-4101-8f39-947ba9b64147</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
