<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Log Out_mainLine</name>
   <tag></tag>
   <elementGuidId>6ac96793-4be6-4924-97c1-545e6153336e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.mainLine</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='hamburger-one']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d5eb3e9f-32c1-4cb3-8dfe-dfb5fa979299</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mainLine</value>
      <webElementGuid>0d0721e1-5aa4-4254-bfc9-fb3cfd9d2bd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hamburger-one&quot;)/span[@class=&quot;mainLine&quot;]</value>
      <webElementGuid>d8d7304e-7158-4974-a139-16be3383f876</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='hamburger-one']/span</value>
      <webElementGuid>88a9aa6d-b0be-4e29-8221-d42a897b5b4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a/span</value>
      <webElementGuid>bad8eadf-82c7-4e7d-bd5f-49ba63320b03</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
